### ISSUE TITLE
Hey man, please stop inviting me to the KA org

### ISSUE THREAD

**Issue by IroncladDev** [tlawson49/IDK#1]
Hey tlawson, I just want to let ya know that I am not active on KA anymore and never will be.  My account LeviathanProgramming has been eternally deleted and I've moved on to replit.

**Comment by tlawson49** [comment]
Hi Conner1115,

I am very sorry for inviting you to the Khan Academy 101 organization. It was nice having you on Khan Academy and I wish you luck in the future!
